# Generated by Django 2.2.4 on 2020-09-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('cateid', models.AutoField(primary_key=True, serialize=False)),
                ('catename', models.CharField(max_length=30, verbose_name='类别名称')),
                ('catestatus', models.IntegerField(default='1', verbose_name='类别状态1-正常,2-已废弃')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
