# Generated by Django 2.2.4 on 2020-09-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catestatus',
            field=models.IntegerField(default=1, verbose_name='类别状态1-正常,2-已废弃'),
        ),
        migrations.AlterField(
            model_name='category',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
