# Generated by Django 2.2.4 on 2020-09-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200913_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('proid', models.AutoField(primary_key=True, serialize=False)),
                ('cateid', models.IntegerField(verbose_name='类别Id')),
                ('name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('mainimage', models.CharField(max_length=500, null=True, verbose_name='产品主图,url相对地址')),
                ('detail', models.CharField(max_length=500, null=True, verbose_name='产品详细图,url相对地址')),
                ('price', models.FloatField(verbose_name='价格')),
                ('stock', models.IntegerField(verbose_name='库存数量')),
                ('status', models.IntegerField(default=1, verbose_name='商品状态.1-在售 2-下架 3-删除')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
        ),
    ]
